<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Account\Enums\" />
    <Folder Include="Features\ArrivalExits\Commands\" />
    <Folder Include="Features\ArrivalExits\Queries\" />
    <Folder Include="Features\Employee\Commands\" />
    <Folder Include="Features\Employee\Queries\" />
    <Folder Include="Features\Vacation\Commands\" />
    <Folder Include="Features\Vacation\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.8" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="8.2.2" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="9.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HRManagement.Application.Web\HRManagement.Application.Web.csproj" />
    <ProjectReference Include="..\HRManagement.Domain\HRManagement.Domain.csproj" />
    <ProjectReference Include="..\HRManagement.Infrastructure.Api\HRManagement.Infrastructure.Api.csproj" />
    <ProjectReference Include="..\HRManagement.Persistence\HRManagement.Persistence.csproj" />
  </ItemGroup>

</Project>
