<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Account\Enums\" />
    <Folder Include="Features\ArrivalExits\Commands\" />
    <Folder Include="Features\ArrivalExits\Queries\" />
    <Folder Include="Features\Employee\Commands\" />
    <Folder Include="Features\Employee\Queries\" />
    <Folder Include="Features\Vacation\Commands\" />
    <Folder Include="Features\Vacation\Queries\" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="AutoMapper" Version="12.0.1" />
	  <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorHRManagement.Api\BlazorHRManagement.Api.csproj" />
    <ProjectReference Include="..\HRManagement.Application.Abstraction\HRManagement.Application.Abstraction.csproj" />
    <ProjectReference Include="..\HRManagement.Application.Web\HRManagement.Application.Web.csproj" />
    <ProjectReference Include="..\HRManagement.Persistence\HRManagement.Persistence.csproj" />
    <ProjectReference Include="..\HRManagement.Shared\HRManagement.Shared.csproj" />
  </ItemGroup>

</Project>
