<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>fc47f527-b8e6-4377-b06b-586a970e296c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HRManagement.Application.Web\HRManagement.Application.Web.csproj" />
    <ProjectReference Include="..\HRManagement.Domain\HRManagement.Domain.csproj" />
    <ProjectReference Include="..\HRManagement.Shared\HRManagement.Shared.csproj" />
  </ItemGroup>

</Project>
