<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MudBlazor" Version="8.*" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="Components\Pages\Personnel\" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\HRManagement.Application.Abstraction\HRManagement.Application.Abstraction.csproj" />
    <ProjectReference Include="..\HRManagement.Application.Web\HRManagement.Application.Web.csproj" />
    <ProjectReference Include="..\HRManagement.Persistence\HRManagement.Persistence.csproj" />
    <ProjectReference Include="..\HRManagement.Shared\HRManagement.Shared.csproj" />
    <ProjectReference Include="..\Implementation\BlazorHRManagement.Implementation.csproj" />
  </ItemGroup>
</Project>