<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Account\Queries\" />
    <Folder Include="Features\ArrivalExits\Commands\" />
    <Folder Include="Features\ArrivalExits\Queries\" />
    <Folder Include="Features\Employee\Commands\" />
    <Folder Include="Features\Employee\Queries\AddEmployee\" />
    <Folder Include="Features\Employee\Queries\DeleteEmployee\" />
    <Folder Include="Features\Employee\Queries\UpdateEmployee\" />
    <Folder Include="Features\Vacation\Commands\" />
    <Folder Include="Features\Vacation\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HRManagement.Application.Abstraction\HRManagement.Application.Abstraction.csproj" />
  </ItemGroup>

</Project>
