//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagement.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRManagement.Shared.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات موفقیت امیز نبود..
        /// </summary>
        public static string App_StringKeys_ٍFailed_Message {
            get {
                return ResourceManager.GetString("App_StringKeys_ٍFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری تکراری است..
        /// </summary>
        public static string App_StringKeys_ٍFailed_Message_DuplicateUsername {
            get {
                return ResourceManager.GetString("App_StringKeys_ٍFailed_Message_DuplicateUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و رمزعبور نباید یکسان باشند..
        /// </summary>
        public static string App_StringKeys_ٍFailed_Message_PasswordAndUsernameDuplicate {
            get {
                return ResourceManager.GetString("App_StringKeys_ٍFailed_Message_PasswordAndUsernameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور باید شامل حداقل یک عدد، یک حرف بزرگ و یک علامت خاص (!@#$&amp;*) باشد.
        /// </summary>
        public static string App_StringKeys_ٍFailed_Message_PasswordValidation {
            get {
                return ResourceManager.GetString("App_StringKeys_ٍFailed_Message_PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string APP_StringKeys_Loading {
            get {
                return ResourceManager.GetString("APP_StringKeys_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string APP_StringKeys_Password {
            get {
                return ResourceManager.GetString("APP_StringKeys_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد..
        /// </summary>
        public static string App_StringKeys_Success_Message {
            get {
                return ResourceManager.GetString("App_StringKeys_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string App_StringKeys_User_Login {
            get {
                return ResourceManager.GetString("App_StringKeys_User_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن کاربر.
        /// </summary>
        public static string App_StringKeys_User_Register {
            get {
                return ResourceManager.GetString("App_StringKeys_User_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string APP_StringKeys_Username {
            get {
                return ResourceManager.GetString("APP_StringKeys_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات فیلد {0} الزامی است..
        /// </summary>
        public static string APP_StringKeys_Validation_Required {
            get {
                return ResourceManager.GetString("APP_StringKeys_Validation_Required", resourceCulture);
            }
        }
    }
}
